version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:3000"
    volumes:
      - ./frontend/src:/app/frontend/src
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app/backend
    #depends_on:
    #  - database  # Add other services if needed

  # Add other services like database if required

# Define additional configurations as needed
