# Use an official Python runtime as a base image
FROM python:3.9-alpine

# Set the working directory to /app
WORKDIR /app/backend

# Copy requirements.txt to /app/backend/
COPY backend/requirements.txt ./

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents to /app/backend/
COPY backend/ .

# Expose port 5000
EXPOSE 5000

# Start the Flask app
CMD ["python", "app.py"]
