# Use an official Node runtime as a base image
FROM node:18-alpine

# Set the working directory to /app
WORKDIR /app/frontend

# Copy package.json and package-lock.json to /app/frontend/
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy the current directory contents to /app/frontend/
COPY frontend/ .

# Expose port 3000
EXPOSE 3000

# Start the Next.js app
CMD ["npm", "run", "dev"]
